services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    networks:
      - net


  api:
    build:
      dockerfile: ./back/Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - ./back:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: sh -c "npm install && npx friend generate && npm run start:migrate:prod"
    ports:
      - 3000:3000
      - 8001:8001
    depends_on:
      - postgres
    networks:
      - net

  front:
    build:
      dockerfile: ./front/Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      #target: development
    volumes:
      - ./front:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: npm run dev
    ports:
      - 5173:5173
    networks:
      - net

volumes:
  docker-nest-postgres:
  pgadmin:
  front:

networks:
  net:
    driver: bridge
