version: '3.8'

services:
  api:
    container_name: api
    build:
      dockerfile: ./back/Dockerfile
      target: development
    env_file:
      - .env
    command: npm run start
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - net

  front:
    container_name: front
    build:
      dockerfile: ./front/Dockerfile
      context: .
      target: production
    # command: npm run start
    volumes:
      - ./front:/usr/src/app
      - ./front/dist:/usr/src/app/dist
    ports:
      - 5173:5173
    depends_on:
      - api
    networks:
      - net

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
    networks:
      - net

volumes:
  docker-nest-postgres:
  dist:


networks:
  net:
    driver: bridge
