services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres


  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: npm run start:migrate:prod
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres


  redis: # Name of container
    image: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

volumes:
  docker-nest-postgres:
  redis:
    driver: local
  pgadmin:
