version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - net

  api:
    container_name: api
    build:
      context: ./back/
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - net
    volumes:
      - ./back:/usr/src/app
      - uploaded-images:/usr/src/app/public/uploads

  front:
    container_name: front
    build:
      context: ./front/
      target: prod
    volumes:
      - ./front:/usr/src/app
      - ./front/dist:/usr/src/app/dist
    depends_on:
      - api
    networks:
      - net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./front/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - uploaded-images:/usr/src/app/public/uploads
    depends_on:
      - front
    networks:
      - net

volumes:
  docker-nest-postgres:
  dist:
  uploaded-images:

networks:
  net:
    driver: bridge
