name: Docker Compose CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]



jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clean up temporary files
      run: |
        sudo chmod -R 777 /home/ubuntu/actions-runner/_work/pong/pong
        sudo rm -rf /home/ubuntu/actions-runner/_work/pong/pong/

      # Add any setup steps you need before running Docker Compose
      
    - name: Build and Run Services with Docker Compose
      env:
        MY_ENV_VARIABLE: ${{ secrets.MY_ENV_VARIABLE }}
      run: |
        echo "$MY_ENV_VARIABLE" > .env
        docker-compose up -d --build

      # Add any post-processing or testing steps you need after running Docker Compose
