name: Build Docker Images

on:
  push:
    branches:
      - 21-workflow-fix-docker-image

jobs:
  build-on-push:
    runs-on: self-hosted

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      DOCKER_SERVER: ${{ secrets.DOCKER_IP }}

    steps:

      - name: Cleaning
        run: |
          sudo chmod -R 777 /home/ubuntu/actions-runner/_work/pong/pong/*
          docker compose down
          if [[ $(docker volume ls -qf dangling=true) ]]; then
          docker volume rm $(docker volume ls -qf dangling=true)
          fi
          
          docker system prune -af
          sudo find /home/ubuntu/actions-runner/_work/pong/pong/* -delete
          sudo rm -rf /home/ubuntu/actions-runner/_work/pong/pong/*
        shell: /usr/bin/bash -e {0}

        continue-on-error: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push API image
        run: |
          echo "$MY_ENV_VARIABLE" > .env
          docker-compose up -d --build
          docker-compose logs
        env:
          MY_ENV_VARIABLE: ${{ secrets.MY_ENV_VARIABLE }}
