name: Build Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      DOCKER_SERVER: 195.15.213.225:2375  
      

    steps:
      - uses: actions/checkout@v3
      - name: Clean up temporary files
        run: |
          sudo chmod -R 777 /home/ubuntu/actions-runner/_work/pong/pong
          sudo rm -rf /home/ubuntu/actions-runner/_work/pong/pong
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push API image
        run: |
          echo "$MY_ENV_VARIABLE" > .env
          docker-compose up -d --build
        env:
          MY_ENV_VARIABLE: ${{ secrets.MY_ENV_VARIABLE }}
