name: Build Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
      PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
      DOCKER_SERVER: 195.15.213.225:2375  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to your Docker server
        run: docker login $DOCKER_SERVER -u your-docker-username -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        run: docker build -t $DOCKER_SERVER/ubuntu/api:latest -f ./back/Dockerfile .
        run: docker push $DOCKER_SERVER/ubuntu/api:latest

      - name: Build and push Frontend image
        run: docker build -t $DOCKER_SERVER/ubuntu/front:latest -f ./front/Dockerfile .
        run: docker push $DOCKER_SERVER/ubuntu/front:latest
